In [1]:
#pip install numpy
import numpy as np

# Create a 1D array
array_1d = np.array([1, 2, 3, 4])
print("1D Array:", array_1d)

# Create a 2D array
array_2d = np.array([[1, 2], [3, 4]])
print("2D Array:\n", array_2d)

# Perform array addition
result = array_1d + 2
print("Array Addition:", result)

# Compute the dot product of two arrays
dot_product = np.dot(array_2d, [[1], [1]])
print("Dot Product:\n", dot_product)

1D Array: [1 2 3 4]
2D Array:
 [[1 2]
 [3 4]]
Array Addition: [3 4 5 6]
Dot Product:
 [[3]
 [7]]


In [2]:
# lists or tuples into NumPy arrays using np.array()
import numpy as np

# From a list
array_from_list = np.array([1, 2, 3, 4])
print(array_from_list)

# From a tuple
array_from_tuple = np.array((5, 6, 7))
print(array_from_tuple)

[1 2 3 4]
[5 6 7]


In [3]:
#Using Built-in Functions
#Zeros and Ones

zeros_array = np.zeros((3, 3))  # 3x3 array of zeros
ones_array = np.ones((2, 4))   # 2x4 array of ones
zeros_array
ones_array

#Empty Array (uninitialized array (values are random)
empty_array = np.empty((2, 2))
empty_array

#full array
full_array = np.full((3, 3), 7)  # 3x3 array filled with 7
print(full_array)

#using range 

#(np.arange(start, stop, step)

range_array = np.arange(1, 10, 2)  
print(range_array)

linspace_array = np.linspace(0, 1, 5)  # equal division btw 0 & 1 into 5 parts
print(linspace_array)

# Random Arrays
random_integers = np.random.randint(0, 10, (3, 3))
print(random_integers)

#Identity and Diagonal Matrice
#4=n (n*n matrix)

identity_matrix = np.eye(4)
print(identity_matrix)

diagonal_matrix = np.diag([1, 2, 3])
print(diagonal_matrix)

[[7 7 7]
 [7 7 7]
 [7 7 7]]
[1 3 5 7 9]
[0.   0.25 0.5  0.75 1.  ]
[[7 3 7]
 [7 7 7]
 [5 5 1]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[1 0 0]
 [0 2 0]
 [0 0 3]]


In [4]:
#Array Properties
arr = np.array([[1, 2, 3], [4, 5, 6]])

print("Array Shape:", arr.shape)  # (2, 3) -> 2 rows, 3 columns
print("Array Size:", arr.size)    # Total number of elements (6)
print("Array Dimensions:", arr.ndim)  # Number of dimensions (2)
print("Data Type:", arr.dtype)    # Data type of elements (int64) #64bit

Array Shape: (2, 3)
Array Size: 6
Array Dimensions: 2
Data Type: int64


In [5]:
#Combining Arrays
import numpy as np

# Create two 3x3 arrays: one filled with zeros, the other with ones
zeros_array = np.zeros((3, 3))
ones_array = np.ones((3, 3))
combined_array = np.hstack((zeros_array, ones_array))
combined_array 

array([[0., 0., 0., 1., 1., 1.],
       [0., 0., 0., 1., 1., 1.],
       [0., 0., 0., 1., 1., 1.]])

In [6]:
#Indexing:Access individual elements

arr = np.array([[10, 20, 30], [40, 50, 60]])
print("Element at (0, 1):", arr[0, 1])

#Slicing:Extract a sub-array
# Extract first row
print("First Row:", arr[0, :])

# Extract first column
print("First Column:", arr[:, 0])

# Extract a 2x2 sub-array
print("Sub-array:\n", arr[0:2, 1:3])

#Reshaping Arrays:Change the dimensions of an array
arr = np.array([1, 2, 3, 4, 5, 6])
reshaped = arr.reshape((2, 3))
print("Reshaped Array:\n", reshaped)

#Boolean Indexing

# Create a 1D array
arr = np.array([10, 20, 30, 40, 50])

# Boolean indexing to select elements greater than 25
selected_elements = arr[arr > 25]
print("Elements greater than 25:", selected_elements)


Element at (0, 1): 20
First Row: [10 20 30]
First Column: [10 40]
Sub-array:
 [[20 30]
 [50 60]]
Reshaped Array:
 [[1 2 3]
 [4 5 6]]
Elements greater than 25: [30 40 50]


In [7]:
#TASK  :Creating a Symmetric Matrix AATRANSPOSE
#Dividing by 2 ensures that the off-diagonal elements are symmetrized

import numpy as np

# Create a random 3x3 matrix
random_matrix = np.random.rand(3, 3)
print("Random Matrix:\n", random_matrix)

# Generate a symmetric matrix by averaging the original matrix and its transpose
symmetric_matrix = (random_matrix + random_matrix.T) / 2
print("Symmetric Matrix:\n", symmetric_matrix)

Random Matrix:
 [[0.55961908 0.45817859 0.12387362]
 [0.56369398 0.89125671 0.21576815]
 [0.84204414 0.61479454 0.4400061 ]]
Symmetric Matrix:
 [[0.55961908 0.51093628 0.48295888]
 [0.51093628 0.89125671 0.41528134]
 [0.48295888 0.41528134 0.4400061 ]]


In [8]:
#TASK 1:
import numpy as np

# Create a 2D array of shape (4, 5) with random integers between 0 and 100
random_array = np.random.randint(0, 80, size=(4, 5))

print("2D Array filled with random integers:")
print(random_array)

2D Array filled with random integers:
[[32 50 15  2 39]
 [38 51 65 77 67]
 [73 25 26 19 50]
 [69 57  7 46 48]]


In [9]:
#TASK2
#TASK:
#Given a 3x2 matrix A and a 1D array B of size 2, perform element-wise multiplication using broadcasting. The elements of B should be applied to each row of A, and the resulting matrix should be printed.
#Input:

#Matrix A: [[1, 2], [3, 4], [5, 6]]
#Array B: [1, 2]
import numpy as np

# Arrays A and B
A = np.array([[1, 2], [3, 4], [5, 6]])
B = np.array([1, 2])

# Matrix multiplication using broadcasting
result = A * B  # Broadcasting automatically scales B across rows of A
print("Matrix Multiplication Result:\n", result)

Matrix Multiplication Result:
 [[ 1  4]
 [ 3  8]
 [ 5 12]]


In [10]:
#SUBMATRIX

# Create a 2D array
arr_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])

# Extract a 2x2 submatrix from the center
submatrix1 = arr_2d[1:3, ]
submatrix = arr_2d[1:3, 1:3]
print("Extracted Submatrix:\n", submatrix)
submatrix1


Extracted Submatrix:
 [[ 6  7]
 [10 11]]


array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [11]:
# Reshaping a 1D Array into a 2D Array
# Create a 1D array with 12 elements
arr = np.arange(1, 13)

# Reshape the 1D array into a 2D array with 3 rows and 4 columns
reshaped_arr = arr.reshape(3, 4)

print("Original Array:", arr)
print("Reshaped Array (3x4):\n", reshaped_arr)


Original Array: [ 1  2  3  4  5  6  7  8  9 10 11 12]
Reshaped Array (3x4):
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [12]:
#Addition, Subtraction, Multiplication, Division :array
# import numpy as np
# Create two arrays
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([5, 6, 7, 8])

# Element-wise addition
add_result = arr1 + arr2

# Element-wise subtraction
sub_result = arr1 - arr2

# Element-wise multiplication
mul_result = arr1 * arr2

# Element-wise division
div_result = arr1 / arr2

print("Addition:", add_result)
print("Subtraction:", sub_result)
print("Multiplication:", mul_result)
print("Division:", div_result)

Addition: [ 6  8 10 12]
Subtraction: [-4 -4 -4 -4]
Multiplication: [ 5 12 21 32]
Division: [0.2        0.33333333 0.42857143 0.5       ]


In [13]:
#Operations with Scalars:You can perform arithmetic operations between an array and a scalar (a single number).
# Scalar addition
print("Add 5 to each element:", arr1 + 5)  # [15, 25, 35]

# Scalar multiplication
print("Multiply each element by 2:", arr1 * 2)  # [20, 40, 60]

Add 5 to each element: [6 7 8 9]
Multiply each element by 2: [2 4 6 8]


In [14]:
#element-wise operation
# Exponentials and logarithms
arr = np.array([1, 2, 3])

print("Exponential:", np.exp(arr)) 
print("Natural Log:", np.log(arr))  

Exponential: [ 2.71828183  7.3890561  20.08553692]
Natural Log: [0.         0.69314718 1.09861229]


In [15]:
#Element-wise Power and Square Root
arr = np.array([1, 4, 9, 16, 25])

# Element-wise square root
sqrt_result = np.sqrt(arr)

# Element-wise power (raise each element to the power of 2)
power_result = np.power(arr, 2)

print("Square Root:", sqrt_result)
print("Power (Squared):", power_result)

Square Root: [1. 2. 3. 4. 5.]
Power (Squared): [  1  16  81 256 625]


In [16]:
#Comparison Operations:Element-wise comparisons return Boolean arrays.
# Comparison operations
arr1 = np.array([10, 20, 30])
arr2 = np.array([15, 20, 25])

print("Greater than:", arr1 > arr2)  # [False, False, True]
print("Less than or equal:", arr1 <= arr2)  # [ True,  True, False]
print("Equality:", arr1 == arr2)

Greater than: [False False  True]
Less than or equal: [ True  True False]
Equality: [False  True False]


In [17]:
#Sum, Mean, Min, Max
arr = np.array([1, 2, 3, 4, 5])

# Sum of all elements
total_sum = np.sum(arr)

# Mean of all elements
mean_value = np.mean(arr)

# Minimum element
min_value = np.min(arr)

# Maximum element
max_value = np.max(arr)

print("Sum:", total_sum)
print("Mean:", mean_value)
print("Min:", min_value)
print("Max:", max_value)

Sum: 15
Mean: 3.0
Min: 1
Max: 5


In [18]:
#TASK
import numpy as np

# Create an array of 10 numbers
numbers = np.array([4, 8, 15, 16, 23, 42, 3, 7, 12, 9])

# Calculate the standard deviation
std_dev = np.std(numbers)

print("Array of numbers:", numbers)
print("Standard Deviation:", std_dev)

Array of numbers: [ 4  8 15 16 23 42  3  7 12  9]
Standard Deviation: 10.97679370308106


In [19]:
#TASK
import numpy as np

# Create two arrays
array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([10, 20, 30, 40, 50])

# Element-wise multiplication
result = array1 * array2

# Sum of the resulting array
result_sum = np.sum(result)

print("Array 1:", array1)
print("Array 2:", array2)
print("Element-wise Multiplication Result:", result)
print("Sum of Result:", result_sum)


Array 1: [1 2 3 4 5]
Array 2: [10 20 30 40 50]
Element-wise Multiplication Result: [ 10  40  90 160 250]
Sum of Result: 550


In [20]:
#DATA PREPROCESSING : 1.Handling Missing Data (Imputation)
# Create an array with missing values (NaN)
data = np.array([1.0, 2.0, np.nan, 4.0, 5.0])

# Replace NaN with the mean of the array
mean_value = np.nanmean(data)
data_cleaned = np.nan_to_num(data, nan=mean_value)

print("Original Data:", data)
print("Cleaned Data:", data_cleaned)

Original Data: [ 1.  2. nan  4.  5.]
Cleaned Data: [1. 2. 3. 4. 5.]


In [21]:
# STANDISATION: (Z-score)

data = np.array([10, 12, 11, 14, 13, 100, 15, 16])
mean = np.mean(data)
std_dev = np.std(data)
z_scores = (data - mean) / std_dev
z_scores

#Mean for Data Normalization(scaling it to a desired range.( when scaling data to the range [0, 1], the mean can be subtracted from the data, and the result is divided by the range of the data (max - min).)
data = np.array([10, 20, 30, 40, 50])
min_val = np.min(data)
max_val = np.max(data)
normalized_data = (data - min_val) / (max_val - min_val)
normalized_data 

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [22]:
#if range changes
a = 10  
b = 20
scaled_data = a + ((data - min_val) * (b - a)) / (max_val - min_val)
scaled_data 

array([10. , 12.5, 15. , 17.5, 20. ])